
''''
  Nombre: Felipe Neri Francisco Bueno González
  Fecha: 18 de septiembre 2023
  Descripción: laboratorio: 2.1.1.19
'''
print("\n    *\n   * *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *****")


print()
print()

print("          *")
print("         * *")
print("        *   *")
print("       *     *")
print("      *       *")
print("     *         *")
print("    *           *")
print("   *             *")
print("  *               *")
print(" *                 *")
print("******         ******")
print("     *         *")
print("     *         *")
print("     *         *")
print("     *         *")
print("     *         *")
print("     *         *")
print("     ***********")
print()
print()
print("    *     "*2)
print("   * *    "*2)
print("  *   *   "*2)
print(" *     *  "*2)
print("***   *** "*2)
print("  *   *   "*2)
print("  *   *   "*2)
print("  *****   "*2)
print()
print()
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print(  *   *")
print("  *   *")
print("  *****")
print()
print()
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print("  *   *")
print("  *   *"
print("  *****")
print()
print()
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
Print("  *   *")
print("  *   *")
print("  *****")
print()
print()
print("    *")
print("   * *")
print("  *   *")
print(" *     *")
print("***   ***")
print('  *   *')
print("  *   *")
print("  *****")
